config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :flat_find, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_find
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :flat_find, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.flat_id = @flat.id
    if @review.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_find
    @flat = Flat.find(params[:flat_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>

<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<h1>All our flats</h1>
<p>All <%= @flats.size %> flats</p>

<div>
  <% @flats.each do |flat| %>
    <div>
      <h3><%= flat.name %></h3>
      <p><%= flat.address %></p>
      <i class="fa-solid fa-users">
        <%= flat.number_of_guests %>
      </i>
      <i class="fa-solid fa-hand-holding-dollar">
        <%= flat.price_per_night %>
      </i>
      <%= link_to "More info", flat_path(flat) %>
      <%= link_to "Edit", edit_flat_path(flat) %>
      <%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h3><%= @flat.address %></h3>
<div>
  <i class="fa-solid fa-users">
    <%= @flat.number_of_guests %>
  </i>
  <i class="fa-solid fa-hand-holding-dollar">
      <%= @flat.price_per_night %>
  </i>
</div>

<h2>A bit more about this flat</h2>
<p><%= @flat.description %></p>

<h2>Reviews:</h2>
<ul>
  <% @flat.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>

<%= link_to "Leave a review", new_flat_review_path(@flat) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h3><%= link_to "Simple Airbnb", flats_path %></h3>
    <%= link_to "Add flat", new_flat_path %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [@flat, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Leave a review</h1>

<%= render "form", review: @review %>